### PR TITLE
Add LICENSE

### PR DESCRIPTION
**Pull request by tekknolagi**
MIT License

### CODE REVIEW

**Comment by rofl0r** [comment]
ping

**Comment by tekknolagi** [comment]
lol, wanting to use Rabbit in your project? Beware, there's probably loads of bugs. I'll merge the license though.

**Comment by rofl0r** [comment]
> Beware, there's probably loads of bugs

oh? it looks so simple, can't be *that* buggy. and even if it is, should be easy to fix.
it certainly looks like something to recommend to people rather than writing their own buggy, badly designed one.

**Comment by tekknolagi** [comment]
Well whatever you do find please report it to me so i can get it fixed
pronto. I'd love to add a comprehensive test suite for the assembler and
vm.

**Comment by tekknolagi** [comment]
Unrelated: how did you stumble across this?

**Comment by rofl0r** [comment]
it's linked on this <strike>amazon book advertisement page</strike> "awesome" "curated list"  https://github.com/aalhour/awesome-compilers

**Pull request merged**
