### PR TITLE
Clean up some compiler warnings

### PR DESCRIPTION
**Pull request by akkartik**

### CODE REVIEW

**Comment by tekknolagi** [comment]
Neat, thanks!

**Comment by tekknolagi** [comment]
Er, I forgot about this bit: rabbit.c is a compiler artifact that is checked in. You should edit rabbitvm.org and regenerate rabbit.c.

**Comment by tekknolagi** [comment]
I've done this and pushed to master.

**Comment by akkartik** [comment]
Ah, thanks!

**Comment by akkartik** [comment]
What toolchain is involved in tangling from Org mode?

**Comment by tekknolagi** [comment]
Running this: `emacs --batch --eval "(require 'org)" --eval '(org-babel-tangle "rabbitvm.org")'`

**Pull request merged**
